name: Build and Upload Go Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  

      - name: Build Go file
     
        run: go mod init gols && go build -o /gols.go  

      - uses: actions/upload-artifact@v4
        with:
          name: go-artifact
          path: ls  

  
