name: Build and Upload Go Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Adjust Go version as needed

      - name: Build Go file
        run: go build -o /gols.go .  # Replace with your Go file name

      - uses: actions/upload-artifact@v4
        with:
          name: go-artifact
          path: ls  # Replace with your Go file name

  
