name: Build and Upload Go Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: 1.20
        
          

      - name: Build Go file
     
        run: go build gols.go -o ls  

      - uses: actions/upload-artifact@v4
        with:
          name: go-artifact
          path: ls  

  
